### ISSUE TITLE
required paths not found...

### ISSUE THREAD

**Issue by Ivan367al** [divpusher/codeigniter4-auth#1]
|Hello,
|I just installed it on my server, but I get this error:
|.....

the original issues being solved (my bad), now everything should be properly installed, but when I try to register, I'm redirected again to the register page with no email being sent and no records inserted in the database.
Any advice about ?

Thanks anyway! Good job!

**Comment by divpusher** [comment]
Hello and thanks!

Maybe your email is not configured properly in **app/Config/Email.php**. Or maybe it's your DB credentials.

I suggest you to check your error logs in **writable/logs** to figure out what the problem is.
