### ISSUE TITLE
How to check whether user is logged in or not globally 

### ISSUE THREAD

**Issue by Asim187** [divpusher/codeigniter4-auth#12]
could you please provide steps or documentation on following

how can i check whether user is logged in or not in all the controller files
and how can i get **user id**  in all the controller and model files 
thanks

**Comment by MisterDuval** [comment]
if logged in;
```
if ($this->session->isLoggedIn) {
	// what you have to do...
}
```
to get user data ID:

`$this->session->get('userData')['id']`
