### ISSUE TITLE
How to customize the template?

### ISSUE THREAD

**Issue by dirbey** [divpusher/codeigniter4-auth#14]
Could you help me on how to customize or change the default template?

**Comment by divpusher** [comment]
There are two ways.

1) Just edit the files in **app/ThirdParty/Auth/Views**.

2) It's also possible to merge it into your project 1-by-1, file-by-file. For example:

- open **app/ThirdParty/Auth/Config/Routes.php**, copy the code
- open your project's **app/Config/Routes.php** and paste the code
- change the route group namespace accordingly (e.g.: from **Auth\Controllers** to **App\Controllers\Auth**)

Etc.

**Comment by dirbey** [comment]
OK thank you so much!!
