### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by Bezzoom** [divpusher/codeigniter4-auth#2]
Hi? Team.

Is there any logs?
How can i troubleshoot this: activation link does not send, any errors at mail server doesn't appiears.
Recepient and sender uses same server. And i use SMTP for sending mail.

**Comment by divpusher** [comment]
Hello! 

CodeIgniter handles all [logging](https://codeigniter4.github.io/userguide/general/logging.html) by default. You should check **/writable/logs/** folder for error logs. Maybe you also need to increase the logging threshold in **/app/Config/Logger.php**

Also double check your SMTP credentials in **/app/Config/Email.php** or in **.env** file if you use that. I once left a space character after a copy paste and I spent an hour to find the issue. :)

**Comment by Bezzoom** [comment]
Ok, I'll check all of you write. And show results to you.
SMTP cred's correct at 100%
