### ISSUE TITLE
Best practice in adjusting views and routes?

### ISSUE THREAD

**Issue by andersdn11** [divpusher/codeigniter4-auth#3]
This was just what i was looking for! Easy to setup. 

For anyone else looking, the only slight issue i ran into was `php spark migrate -all` was throwing an error: _No such file or directory_

I only needed to change `localhost` to `127.0.0.1` in my .env database settings. And Voila!

For the author, if i want to redirect to a custom admin view instead of account after login, or i need to change the default view files included in the library, how would i go about that, just hack away in the library files ?

**Comment by divpusher** [comment]
Hello!

Yes, just modify them.  E.g.: edit **app/ThirdParty/Auth/Controllers/LoginController.php** line #92 to change the destination of redirect.
