### ISSUE TITLE
How to publish this to view, controllers, and model?

### ISSUE THREAD

**Issue by qib-tech** [divpusher/codeigniter4-auth#4]

**Comment by divpusher** [comment]
If you don't want to use it as a 3rd party library, it's possible to merge it into your project 1-by-1, file-by-file. 

For example:

- open **codeigniter4-auth/Auth/Config/Routes.php**, copy the code 
- open your project's **app/Config/Routes.php** and paste the code
- change the route group namespace accordingly (e.g.: from **Auth\Controllers** to **App\Controllers\Auth**)

Etc.

**Comment by qib-tech** [comment]
i did it thanks for reply
