### ISSUE TITLE
error at /register at submit form

### ISSUE THREAD

**Issue by alejandromunoz** [divpusher/codeigniter4-auth#5]
ErrorException
Declaration of Auth\Models\UserModel::setValidationRules(string $rules) should be compatible with CodeIgniter\Model::setValidationRules(array $validationRules) 

![errorregisterform](https://user-images.githubusercontent.com/210786/88020725-d7857c00-caf1-11ea-8ab1-cc91a2ece1e6.jpg)

**Comment by adigamara24** [comment]
U can redownload, and replace file :
- Models\UserModel
- Controllers\RegistrationController
- Controllers\AccountController

The error is using the setValidationRules which does not need to be regenerated in a model.

If you want to make it dynamic, just return the data to the controller

**Comment by divpusher** [comment]
Thank you for the help @adigamara24 !

This issue should be fixed now.

**Comment by adigamara24** [comment]
You're welcome

**Comment by alejandromunoz** [comment]
Thank you! i will test today!

**Comment by adigamara24** [comment]
Success for u
