### ISSUE TITLE
Cannot run migrate?

### ISSUE THREAD

**Issue by blaasvaer** [divpusher/codeigniter4-auth#9]
Hi,
I get this:

```
Fatal error: Uncaught Error: Call to undefined function CodeIgniter\locale_set_default() in /Applications/MAMP/htdocs/my_app/system/CodeIgniter.php:184
```

when running:

```
php spark migrate
```

How do I go about that?

**Comment by divpusher** [comment]
Hello! Please do a google search about your issue. It has nothing to do with this library probably.

**Comment by MisterDuval** [comment]
You need to respect requirements of Codeigniter 4, please add intl extension to your MAMP:
extension=intl

**Comment by MisterDuval** [comment]
@divpusher this ticket can be closed

**Comment by divpusher** [comment]
Thanks!
